#!/usr/bin/env bash
# PreToolUse hook (matcher: Edit|Write|MultiEdit|NotebookEdit)
# Blocks AI edits to files that humans must own: secrets, lockfiles, CI
# policy, and generated artifacts. Exit code 2 = block and show the reason
# to Claude; exit code 0 = allow.
#
# Input: hook JSON on stdin (tool_name, tool_input.file_path, ...)
# Docs: https://code.claude.com/docs/en/hooks
set -euo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')"

[ -z "$file_path" ] && exit 0

# Normalise to a repo-relative path when possible.
root="${CLAUDE_PROJECT_DIR:-$(pwd)}"
rel="${file_path#"$root"/}"

# Documentation copies of env files are fine to edit.
if printf '%s' "$rel" | grep -Eq '(^|/)\.env\.(example|sample|template)$'; then
  exit 0
fi

# Patterns humans must change by hand (extend in AGENTS.md "Protected paths").
protected_patterns=(
  '(^|/)\.env($|\.)'                # .env, .env.local, .env.production
  '(^|/)\.envrc$'
  '(^|/)secrets?(/|$)'              # secrets/ directory
  '\.(pem|key|p12|pfx|jks)$'
  '(^|/)(package-lock|pnpm-lock|yarn\.lock|uv\.lock|poetry\.lock|Cargo\.lock|go\.sum|Gemfile\.lock|composer\.lock)'
  '(^|/)\.github/CODEOWNERS$'
  '(^|/)scripts/rulesets/'          # branch protection policy
  '(^|/)\.claude/settings\.json$'   # team policy: edit via PR by humans
  '(^|/)LICENSE$'
)

for pat in "${protected_patterns[@]}"; do
  if printf '%s' "$rel" | grep -Eq "$pat"; then
    cat >&2 <<MSG
BLOCKED by plugins/team-ai-workflow/scripts/protect-files.sh: "$rel" is a protected path.
Lockfiles are regenerated by the package manager (never edited by hand),
secrets/.env files must never be written by an agent, and policy files
(CODEOWNERS, rulesets, .claude/settings.json) change only via a human-authored PR.
If this change is genuinely required, ask the user to make it manually.
MSG
    exit 2
  fi
done

exit 0
