#!/usr/bin/env bash
# Diagnose the latest failed CI run of a PR and let Claude fix the root cause in a worktree.
# With --post: push a fix PR targeting the PR branch, or comment the diagnosis when nothing could be fixed.
# Usage: scripts/ai/fix-ci.sh <pr-number> [--post]
set -euo pipefail
# shellcheck source=scripts/ai/common.sh
. "$(dirname "$0")/common.sh"
ai_need gh jq claude git
PR="${1:?pr number}"; POST=0; [ "${2:-}" = "--post" ] && POST=1
cd "$(ai_root)"
ai_log "backend: $(ai_backend)"
head="$(gh pr view "$PR" --json headRefName -q .headRefName)"
run_id="$(gh run list --branch "$head" --workflow CI --limit 5 --json databaseId,conclusion -q '[.[] | select(.conclusion=="failure")][0].databaseId' 2>/dev/null || true)"
if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then ai_warn "no failed CI run found for branch $head"; exit 0; fi
log_file="$(mktemp)"; gh run view "$run_id" --log-failed 2>/dev/null | tail -c 40000 > "$log_file" || true
ts="$(date +%Y%m%d%H%M)"; fix_branch="ai/ci-fix-$(printf '%s' "$head" | tr -cd 'a-zA-Z0-9/_.-')-${ts}"
wt="$(ai_worktree "ai-ci-fix-${PR}" "$fix_branch" "origin/$head")"
ai_log "worktree: $wt (branch $fix_branch from origin/$head), failed run $run_id"

prompt="$(cat <<PROMPT
$(ai_untrusted_banner)
CI failed for pull request #$PR (branch $head), run $run_id. The failed-job logs are in the file: $log_file (read it; it may be truncated).
Follow the /fix-ci procedure:
1. Classify: this diff broke it / pre-existing on the base branch / infrastructure. Reproduce with \`make check\`.
2. Fix the ROOT CAUSE with a minimal change. Never skip, disable, loosen or quarantine tests; never add || true; never edit .github/workflows or protected paths.
3. Re-run \`make check\`. Commit only if it passes, with a conventional message like "fix(ci): <cause> (#$PR)". Never push.
4. If you cannot fix it, or it is pre-existing/infra, make NO commits and explain the diagnosis.
Finish with: root cause, what you changed, evidence (commands + output).
PROMPT
)"
export AI_PERMISSION_MODE="${AI_PERMISSION_MODE:-acceptEdits}"
export AI_ALLOWED_TOOLS="${AI_ALLOWED_TOOLS:-Read,Glob,Grep,Edit,MultiEdit,Write,Bash(make *),Bash(git status *),Bash(git diff *),Bash(git log *),Bash(git add *),Bash(git commit *)}"
export AI_MAX_TURNS="${AI_MAX_TURNS:-40}"
report="$( cd "$wt" && ai_run "$prompt" )" || { ai_warn "fix run failed"; rm -f "$log_file"; exit 1; }
rm -f "$log_file"; printf '%s\n' "$report"

commits="$(git -C "$wt" rev-list --count "origin/$head..HEAD" 2>/dev/null || echo 0)"
if [ "$POST" = 1 ]; then
  if [ "$commits" != 0 ]; then
    git -C "$wt" push -u origin "$fix_branch" >/dev/null 2>&1
    url="$(gh pr create --base "$head" --head "$fix_branch" --title "fix(ci): proposed fix for failing checks (#$PR)" --body "$(printf 'Proposed by headless Claude Code for #%s (run %s).\n\n%s\n\n## AI assistance disclosure\n- [x] AI-generated by an agent (Claude Code). Human owner: the PR author.\n' "$PR" "$run_id" "$report")" --label ai:generated)"
    gh pr comment "$PR" --body "CI fix proposed in $url (merge it into \`$head\` if it is right)." >/dev/null
    ai_log "fix PR: $url"
  else
    gh pr comment "$PR" --body "$(printf '**CI diagnosis (AI-assisted, advisory)** for run %s\n\n%s\n' "$run_id" "$report")" >/dev/null
    ai_log "diagnosis comment posted on #$PR"
  fi
else
  ai_log "dry run: $commits commit(s) in $wt. Re-run with --post to open a fix PR / post the diagnosis."
fi
