#!/usr/bin/env bash
# Implement an issue with Claude in an isolated git worktree. With --post: push + open a DRAFT PR + move labels.
# Usage: scripts/ai/implement.sh <issue-number> [--post]
set -euo pipefail
# shellcheck source=scripts/ai/common.sh
. "$(dirname "$0")/common.sh"
ai_need gh jq claude git
ISSUE="${1:?issue number}"; POST=0; [ "${2:-}" = "--post" ] && POST=1
cd "$(ai_root)"
ai_log "backend: $(ai_backend)"
default="$(ai_default_branch)"
ts="$(date +%Y%m%d%H%M)"
branch="ai/issue-${ISSUE}-${ts}"
wt="$(ai_worktree "ai-issue-${ISSUE}" "$branch" "origin/$default")"
ai_log "worktree: $wt (branch $branch from origin/$default)"
[ "$POST" = 1 ] && gh issue edit "$ISSUE" --remove-label ai:ready --add-label ai:in-progress >/dev/null 2>&1 || true

issue_json="$(gh issue view "$ISSUE" --json number,title,body,labels,comments --jq '{number,title,body,labels:[.labels[].name],comments:[.comments[] | {author:.author.login, body:.body}]}')"
prompt="$(cat <<PROMPT
$(ai_untrusted_banner)
Implement GitHub issue #$ISSUE in this working copy (branch $branch). Follow the /implement-issue procedure:
1. Restate goal, acceptance criteria, scope, out-of-scope in a few bullets.
2. Explore the relevant code and copy existing patterns.
3. Write tests that encode the acceptance criteria first, then the minimal implementation.
4. Run \`make check\`; only commit when it passes. Use conventional commit messages that reference #$ISSUE.
5. Never edit protected paths (.env*, lockfiles, CODEOWNERS, scripts/rulesets, .claude/settings.json). Never push.
6. Finish with a short report: what changed, exact commands run and results, what is intentionally not done.
Issue (JSON): $issue_json
PROMPT
)"
export AI_PERMISSION_MODE="${AI_PERMISSION_MODE:-acceptEdits}"
export AI_ALLOWED_TOOLS="${AI_ALLOWED_TOOLS:-Read,Glob,Grep,Edit,MultiEdit,Write,Bash(make *),Bash(git status *),Bash(git diff *),Bash(git log *),Bash(git add *),Bash(git commit *),Bash(gh issue view *)}"
export AI_MAX_TURNS="${AI_MAX_TURNS:-60}"
report="$( cd "$wt" && ai_run "$prompt" )" || { ai_warn "implementation run failed"; [ "$POST" = 1 ] && gh issue edit "$ISSUE" --remove-label ai:in-progress --add-label ai:needs-human >/dev/null 2>&1 || true; exit 1; }
printf '%s\n' "$report"

commits="$(git -C "$wt" rev-list --count "origin/$default..HEAD" 2>/dev/null || echo 0)"
if [ "$commits" = 0 ]; then
  ai_warn "no commits were made; nothing to push"
  [ "$POST" = 1 ] && gh issue edit "$ISSUE" --remove-label ai:in-progress --add-label ai:needs-human >/dev/null 2>&1 && gh issue comment "$ISSUE" --body "The agent could not produce a verified change. A human needs to look. Re-apply \`ai:ready\` to retry after refining the issue." >/dev/null
  exit 2
fi
ai_log "$commits commit(s) on $branch"
if [ "$POST" = 1 ]; then
  git -C "$wt" push -u origin "$branch" >/dev/null 2>&1
  title="$(gh issue view "$ISSUE" --json title -q .title | sed -E 's/^\[[^]]*\]:? *//' | cut -c1-60)"
  case "$(gh issue view "$ISSUE" --json labels -q '[.labels[].name]|join(",")')" in *type/bug*) type=fix ;; *type/docs*) type=docs ;; *type/chore*) type=chore ;; *) type=feat ;; esac
  body="$(printf 'Closes #%s\n\n## Summary\nImplemented headlessly by Claude Code (%s) from the issue acceptance criteria.\n\n## How it was tested\n%s\n\n## AI assistance disclosure\n- [x] AI-generated by an agent (Claude Code). Human owner: the person who ran this.\n' "$ISSUE" "$(ai_backend | cut -d'(' -f1)" "$(printf '%s' "$report" | tail -40)")"
  url="$(gh pr create --draft --base "$default" --head "$branch" --title "$type: $title (#$ISSUE)" --body "$body" --label ai:generated)"
  gh issue edit "$ISSUE" --remove-label ai:in-progress --add-label ai:review >/dev/null 2>&1 || true
  gh issue comment "$ISSUE" --body "Draft PR opened for human review: $url" >/dev/null
  ai_log "draft PR: $url"
else
  ai_log "dry run: branch $branch is ready in $wt. Inspect it, then re-run with --post (or push and open a PR yourself)."
fi
